import "@/styles/reset.scss";
import Layout from "@/utils/Layout/Layout";
import { AnimatePresence } from "framer-motion";
import Head from "next/head";

export default function App({ Component, pageProps, router }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <AnimatePresence mode="wait">
          <Component key={router} {...pageProps} />
        </AnimatePresence>
      </Layout>
    </>
  );
}
